### ISSUE TITLE
Are the pseudo pairs used in the training process of the cell instance segmentation model?

### ISSUE THREAD

**Issue by Mariosz2** [Lewislou/cellseg-sribd#1]
Pseudo pairs are for the training process of the cell classification model to improve the effect. But I want to know whether the pseudo pairs are used in the training process of the cell instance segmentation model, such as in the pre-training process or in the process of fine-tuning the four categories.

**Comment by Lewislou** [comment]
We have tried to use pseudo pairs in the training of segmentation, but we did not find any significant improvement by using them. Therefore, in our final solution, we do not use pseudo pairs in the segmentation stage.

**Comment by Mariosz2** [comment]
Thank you for your explanation, but for Class 1, if there are no pseudo pairs involved, the number of training samples is very small(Class 1 obtained using `unsup_classification.py`), what should be done?
`ReadMe.md` says "For class 1 train the convnext-hover from scratch using classified class 3 data." It refers to directly using Class 1 ("using classified class 3 data" is a typo?) as the training set from scratch Training, instead of pre-training with all images and then fine-tuning on class 1?

**Comment by Lewislou** [comment]
Yes, the number of training samples in class 1 of the competition is small. But in the segmentation training process, we bring in public datasets. so the overall training samples are enough.
Sorry about the type "using classified class 3 data". The codes are the training from scratch codes for convnext-hover, we pretrained the model using all the training images and then finetuned on samples of class 1. The training codes are the same.

**Comment by Mariosz2** [comment]
Yes, I put Cell-seg, Cellpose, Omnipose and Startorius into a folder and run `unsup_classification.py`. The result is that all images of Omnipose and Startorius were classified into class 0 because they are with a single channel, and all images of Cellpose were classified into class colored, but only a few images of Cell-seg competition were classified into class 1. I want to know what's wrong with this classification result.
In addition, the paper seems to conflict with the code `unsup_classification.py`. The paper says "If the mean saturation of an image is **larger than $θ$** and the mean value of the image is within a range of ($α_s$, $α_l$), then it is classified as a gray image (Class 1).", but the code as follows says if s.mean() is more than 0.1 then classify it as a color image.
```
if s.mean() > 0.1 or (v.mean()<0.1 or v.mean() > 0.6):
    shutil.copyfile(path + img_name, colored_path + img_name)
else:
    shutil.copyfile(path + img_name, gray_path + img_name)
```

**Comment by Lewislou** [comment]
Sorry about the misunderstanding. Yes, only a few images are classified into class 1, but with the pre-training of all the samples, the segmentation performance of class 1 can be well developed. The ">/<" expression might be a typo mistake in the paper, we will correct it soon, thanks for informing us~

**Comment by Mariosz2** [comment]
Thanks for your enthusiasm!
